set_property PACKAGE_PIN V19 [get_ports S3]
set_property PACKAGE_PIN U19 [get_ports S2]
set_property PACKAGE_PIN E19 [get_ports S1]
set_property PACKAGE_PIN U16 [get_ports S0]
set_property PACKAGE_PIN U1 [get_ports A1]
set_property PACKAGE_PIN W2 [get_ports A0]
set_property PACKAGE_PIN T1 [get_ports A2]
set_property PACKAGE_PIN R2 [get_ports A3]
set_property PACKAGE_PIN V16 [get_ports B1]
set_property PACKAGE_PIN W16 [get_ports B2]
set_property PACKAGE_PIN V17 [get_ports B0]
set_property PACKAGE_PIN W17 [get_ports B3]
set_property PACKAGE_PIN U15 [get_ports C_out3]

set_property IOSTANDARD LVCMOS33 [get_ports S3]
set_property IOSTANDARD LVCMOS33 [get_ports B0]
set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property IOSTANDARD LVCMOS33 [get_ports B2]
set_property IOSTANDARD LVCMOS33 [get_ports B3]
set_property IOSTANDARD LVCMOS33 [get_ports C_out3]
set_property IOSTANDARD LVCMOS33 [get_ports A0]
set_property IOSTANDARD LVCMOS33 [get_ports A1]
set_property IOSTANDARD LVCMOS33 [get_ports S1]
set_property IOSTANDARD LVCMOS33 [get_ports A2]
set_property IOSTANDARD LVCMOS33 [get_ports S2]
set_property IOSTANDARD LVCMOS33 [get_ports A3]

set_property IOSTANDARD LVCMOS33 [get_ports S0]

